export const FETCH_TEAMS = "FETCH_TEAMS";
export const FETCH_EAST_STANDINGS = "FETCH_EAST_STANDINGS";
export const FETCH_WEST_STANDINGS = "FETCH_WEST_STANDINGS";
export const FETCH_PLAYERS = "FETCH_PLAYERS";
export const FETCH_PLAYER_STATS = "FETCH_PLAYER_STATS";
export const FETCH_TEAM_STATS = "FETCH_TEAM_STATS";
export const FETCH_TEAM_LEADERS = "FETCH_TEAM_LEADERS";
